site_name: ChooChoo Documentation
site_description: 'Documentation site for ChooChoo the checklist tool'
site_author: 'Lucy Whalley'
docs_dir: docs/
repo_name: 'lucydot/choochoo'
repo_url: 'https://github.com/lucydot/choochoo'
nav:
    - Home: index.md
    - Introduction: intro.md
    - Instructors:
      - Setup: instructors/setup.md
      - Questions: instructors/questions.md
      - Tutorials: instructors/tutorials.md
      - Links: instructors/links.md
      - Plots: instructors/plots.md
      - Commands: instructors/commands.md
    - Students: 
      - Setup: students/setup.md
      - Questions: students/questions.md
      - Commands: students/commands.md
    - Tools: tools.md
    - Pedagogy: pedagogy.md
    - Contributing: developers.md
    - Citation: citation.md

theme:
  name: 'material'
