site_name: ChooChoo Documentation
site_description: 'Documentation site for ChooChoo the checklist tool'
site_author: 'Lucy Whalley'
docs_dir: docs/
repo_name: 'lucydot/choochoo'
repo_url: 'https://github.com/lucydot/choochoo'
nav:
    - Home: index.md
    - Introduction: intro.md
    - Quickstart: 
      - Student: quickstart/student
      - Instructor: quickstart/instructor
    - Tools: tools.md
    - Commands: commands.md
    - Citation: citation.md
    - License: license.md
    - Developers: developers.md
theme:
  name: 'material'
