name: Fat Controller

on: 
  workflow_dispatch:

  issues:
    types: 
    - labeled
    
  issue_comment:
    types: 
    - created
    
jobs:
  check_instructor_ticket:
    if: github.event.label.name == 'instructor' 
    runs-on: ubuntu-latest
    env: 
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install .
    - run: ${{ format('python ./scripts/check_instructor_ticket.py {0}', github.actor) }}
      
  check_student_ticket:
    if: github.event.label.name == 'student' 
    runs-on: ubuntu-latest
    env: 
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install .
    - run: ${{ format('python ./scripts/check_student_ticket.py {0}', github.actor) }}
    
  not_issue_owner:
    if: |
      github.event_name == 'issue_comment' && 
      github.actor != github.event.issue.user.login &&
      startsWith(github.event.comment.body,'choochoo ')
    runs-on: ubuntu-latest
    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "[checks ticket] I'm afraid you don't have permission to run choochoo commands here."
        GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
    
  not_instructor_student:
    if: |
      github.event_name == 'issue_comment' && 
      github.actor == github.event.issue.user.login &&
      !contains( github.event.pull_request.labels.*.name, 'instructor') &&
      !contains( github.event.pull_request.labels.*.name, 'student') &&
      startsWith(github.event.comment.body,'choochoo ')
    runs-on: ubuntu-latest
    env: 
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "[checks ticket] To run choochoo commands your issue must be labelled with `instructor` or `student`"
        GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

  choochoo:
    if: |
      github.event_name == 'issue_comment' && 
      github.actor == github.event.issue.user.login &&
      (
        contains( github.event.pull_request.labels.*.name, 'instructor') ||
        contains( github.event.pull_request.labels.*.name, 'student')
      ) &&
      startsWith(github.event.comment.body,'choochoo ')
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install .
    - run: ${{ github.event.comment.body }}
    
  print_context:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - run: echo "$GITHUB_CONTEXT"

