name: Fat Controller

on: 
  issues:
    types: created
  issue_comment:
    types: created
    
jobs:
      
  check-ticket:
    if: |
      github.event_name == issues && 
      github.event.issue_comment.issue.label.name == "instructor"
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install .
    - run: ${{ format(python ./scripts/check_ticket.py {0}, github.actor) }}
    
  choochoo:
    if: |
      github.event_name == issue_comment && 
      github.actor == github.event.issue_comment.issue.owner &&
      startsWith(github.event.comment.body,'choochoo ')
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install .
    - run: ${{ github.event.comment.body }}
    
  no-choochoo-command:
    if: !startsWith(github.event.comment.body,'choochoo ')
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python ./scripts/no_choochoo.py
    
  not-issue-owner:
   if: |
     github.event_name == issue_comment && 
     github.actor != github.event.issue_comment.issue.owner &&
   runs-on: ubuntu-latest
   env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   steps:
   - uses: actions/setup-python@v2
     with:
       python-version: '3.x'
   - run: python ./scripts/not_owner.py
    
    
  
    
