name: Compile tutorial and publish

on:
  push:
    paths:
      - 'tutorials/*'
    branches:    
      - 'main'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert 
    - name: Convert notebook
      env:
        GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
         jupyter nbconvert --to html ./tutorials/*.ipynb  
         rm ./tutorials/*.ipynb 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: tutorials # The folder the action should deploy.
        target-folder: tutorials
        commit-message: build tutorials
        clean: false
        git-config-name: choochoo-bot
        git-config-email:  <>




