name: Compile tutorial and publish

on:
  push:
    paths:
      - 'tutorials/**'
    branches:    
      - 'main'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert 
    - name: Convert notebook
      env:
        GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
         jupyter nbconvert --to html ./tutorials/**.ipynb       
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: choochoo-bot
        message: "Convert notebook to html and publish"
        add: "./tutorials/**"
        push: origin gh_pages --set-upstream --force
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}



